version: '3.3'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'bitbucket'
      MYSQL_USER: 'bitbucketuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'